### ISSUE TITLE
Initiate all transfers before blocking on completion

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/packer-plugin-digitalocean#125]
Currently, when we distribute images to all regions, we do so one at a time. After each transfer is initiated, we wait until it is completed to start the next one. These transfers can happen in parallel. This would have a few benefits.  Large images transferred to many regions may take quite awhile to complete. Currently, if we timeout, the build may fail before initiating all transfers. Also, if a single transfer errors, the others are never initiated.

Surfaced from this related issue: https://github.com/digitalocean/packer-plugin-digitalocean/issues/122#issuecomment-1934183863

**Comment by Davis-A** [comment]
Hello, 

As a suggestion, could this be implemented (or have an option to) not wait for transfer, and instead issue the transfer requests and exit successfully?  Reasoning being with large images (ours are >15GB) it's quite likely it will take longer than the 20 minute timeout.  @wolfsage's example in #122 is our desired behaviour.
