### ISSUE TITLE
20 minutes isn't enough time to transfer images

### ISSUE THREAD

**Issue by lattwood** [digitalocean/packer-plugin-digitalocean#129]
20 minutes isn't enough time to transfer images, as evidenced by our failures to transfer images from SFO3 to NYC1.

https://github.com/digitalocean/packer-plugin-digitalocean/blob/e33984bc61aaa8490a2935bb4a1d2fe8e86f97cd/builder/digitalocean/step_snapshot.go#L101

That needs to be raised or configurable, and is currently blocking image updates on our end.

**Comment by andrewsomething** [comment]
Good call @lattwood. We should make that configurable. Relatedly, this PR will initiate transfers in parallel and provide an option to not block until it completes: https://github.com/digitalocean/packer-plugin-digitalocean/pull/126

**Comment by andrewsomething** [comment]
With the v1.3.0 release, there is now a `transfer_timeout` option. The default was also bumped up to 30 minutes. Additionally, you can set `wait_snapshot_transfer` to `false` to not block on transfer status at all if desired. 

https://github.com/digitalocean/packer-plugin-digitalocean/releases/tag/v1.3.0
