### ISSUE TITLE
Snapshot Tags

### ISSUE THREAD

**Issue by andiempettJISC** [digitalocean/packer-plugin-digitalocean#33]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently we can tag droplets as they are created by packer. It would also be great to have the resultant image snapshots have tags

#### Use Case(s)

Tags could then be used to filter snapshots for further management by other tools (for example terraform data `digitalocean_images`)

#### Potential configuration

```
```

#### Potential References
https://docs.digitalocean.com/reference/api/api-reference/#operation/tag_resource

**Comment by Bryan-Lester-Dolby** [comment]
Hi, it is indeed possible to tag a snapshot, the DO API is just inconsistent and considers snapshots to be "images". The API call looks like:

`curl -X POST   -H "Content-Type: application/json"   -H "Authorization: Bearer $DIGITALOCEAN_TOKEN"   -d '{"resources":[{"resource_id":"$ID","resource_type":"image"}]}'   "https://api.digitalocean.com/v2/tags/$TAG/resources"`

Can we get this functionality? It's common on other builders (AWS, Oracle, etc) and a major stumbling block to those of us that have a lot of images in DO and need to filter them.

**Comment by Bryan-Lester-Dolby** [comment]
This ended up bothering me enough to make a PR using @andiempettJISC 's suggestion. Please review!
