### ISSUE TITLE
Add ability to specify base image by name

### ISSUE THREAD

**Issue by dm3ch** [digitalocean/packer-plugin-digitalocean#49]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
Right now builder supports referencing base images only by ID or by Slug. But slug couldn't be used for self-built images, as far as I found in docs.

*In current documentation it seems that using image name is possible, but it isn't so* - https://github.com/hashicorp/packer-plugin-digitalocean/blob/main/builder/digitalocean/config.go#L43-L47

#### Use Case(s)
It would allow referencing image without ID for self-built base images.

#### Potential configuration

```
```

#### Potential References
https://github.com/digitalocean/godo/issues/521

**Comment by andrewsomething** [comment]
This seems like it might be a good fit for the new-ish  Data Source component type.

https://www.hashicorp.com/blog/announcing-the-packer-data-source-component-type
